version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bagdoor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: sh -c "sleep 5 && ./bot"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: