// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/telegram": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация через Telegram",
                "parameters": [
                    {
                        "description": "Init data от Telegram",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http_auth.TelegramAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_auth.TelegramAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid signature",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "User error или Token error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flights": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Получить все рейсы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http_flight.FlightFullResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении рейсов",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Создать рейс",
                "parameters": [
                    {
                        "description": "Данные рейса",
                        "name": "flight",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http_flight.FlightRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_flight.FlightResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный JSON или формат даты",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Неверный или отсутствует токен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при создании рейса",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flights/moderated": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Получить только отмодерированные рейсы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http_flight.FlightFullResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении рейсов",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Получить все заказы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http_order.OrderFullResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при получении заказов",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Создать заказ",
                "parameters": [
                    {
                        "description": "Данные заказа",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http_order.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_order.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный JSON или формат дат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Невалидный токен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при создании заказа",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders/approved": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Получить только одобренные заказы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http_order.OrderFullResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при получении заказов",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_auth.TelegramAuthRequest": {
            "type": "object",
            "properties": {
                "init_data": {
                    "type": "string"
                }
            }
        },
        "http_auth.TelegramAuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "http_flight.FlightFullResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "flight_date": {
                    "type": "string"
                },
                "flight_number": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "map_url": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "publisher_tg_id": {
                    "type": "integer"
                },
                "publisher_username": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http_flight.FlightRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Лечу налегке, могу взять документы."
                },
                "destination": {
                    "type": "string",
                    "example": "Москва"
                },
                "flight_date": {
                    "description": "dd/mm/yy",
                    "type": "string",
                    "example": "10/06/25"
                },
                "origin": {
                    "type": "string",
                    "example": "Санкт-Петербург"
                }
            }
        },
        "http_flight.FlightResponse": {
            "type": "object",
            "properties": {
                "flight_number": {
                    "type": "string",
                    "example": "Рейс #1234-5678"
                },
                "id": {
                    "type": "integer",
                    "example": 17
                }
            }
        },
        "http_order.OrderFullResponse": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "deposit": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "destination_city": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "media_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "order_number": {
                    "type": "string"
                },
                "origin_city": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "publisher_tg_id": {
                    "type": "integer"
                },
                "publisher_username": {
                    "type": "string"
                },
                "reward": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/order.ModerationStatus"
                },
                "store_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/order.OrderType"
                }
            }
        },
        "http_order.OrderRequest": {
            "type": "object",
            "properties": {
                "cost": {
                    "description": "Стоимость товаров (только для типа store)",
                    "type": "number",
                    "example": 1500
                },
                "deposit": {
                    "description": "Депозит (только для типа personal)",
                    "type": "number",
                    "example": 500
                },
                "description": {
                    "description": "Описание задачи",
                    "type": "string",
                    "example": "Нужно привезти документы из Москвы в Санкт-Петербург"
                },
                "destination_city": {
                    "description": "Город назначения",
                    "type": "string",
                    "example": "Санкт-Петербург"
                },
                "end_date": {
                    "description": "Конец периода",
                    "type": "string",
                    "example": "05/06/25"
                },
                "origin_city": {
                    "description": "Город отправления",
                    "type": "string",
                    "example": "Москва"
                },
                "reward": {
                    "description": "Вознаграждение исполнителю",
                    "type": "number",
                    "example": 100
                },
                "start_date": {
                    "description": "Начало периода",
                    "type": "string",
                    "example": "01/06/25"
                },
                "store_link": {
                    "description": "Ссылка на магазин (только для типа store)",
                    "type": "string",
                    "example": "https://store.com/item/123"
                },
                "title": {
                    "description": "Заголовок заказа",
                    "type": "string",
                    "example": "Заказ на доставку"
                },
                "type": {
                    "description": "Тип заказа: \"personal\" или \"store\"\n🔷 Для \"store\" обязательны поля ` + "`" + `cost` + "`" + ` и ` + "`" + `store_link` + "`" + `\n🔷 Для \"personal\" обязателен ` + "`" + `deposit` + "`" + `",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.OrderType"
                        }
                    ],
                    "example": "personal"
                }
            }
        },
        "http_order.OrderResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "order_number": {
                    "type": "string"
                }
            }
        },
        "order.ModerationStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "APPROVED",
                "REJECTED"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusApproved",
                "StatusRejected"
            ]
        },
        "order.OrderType": {
            "type": "string",
            "enum": [
                "personal",
                "store"
            ],
            "x-enum-varnames": [
                "OrderTypePersonal",
                "OrderTypeStore"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
